# Generated by Django 4.0.6 on 2022-07-26 07:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('areacode', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Code')),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('iemi_number', models.BigIntegerField(blank=True, default=None, null=True)),
                ('service_provider', models.TextField(blank=True, default=None, max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='joining_date',
        ),
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='trials.area'),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_devices',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='trials.device'),
        ),
    ]
