# Generated by Django 4.0.6 on 2022-07-26 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0002_area_channel_device_remove_user_joining_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.RemoveField(
            model_name='area',
            name='areacode',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mpos_user_number',
        ),
        migrations.AddField(
            model_name='area',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='CODE'),
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='NAME OF THE DEVICE'),
        ),
        migrations.AddField(
            model_name='user',
            name='alternate_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name=' ALTERNATE PHONE NUMBER'),
        ),
        migrations.AddField(
            model_name='user',
            name='mpos_user_name',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='MPOS USER NAME'),
        ),
        migrations.AlterField(
            model_name='area',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='DESCRIPTION'),
        ),
        migrations.AlterField(
            model_name='device',
            name='iemi_number',
            field=models.BigIntegerField(blank=True, default=None, null=True, verbose_name='IEMI NUMBER'),
        ),
        migrations.AlterField(
            model_name='device',
            name='service_provider',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True, verbose_name='NETWORK PROVIDER'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True, verbose_name='ADDRESS'),
        ),
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trials.area'),
        ),
        migrations.AlterField(
            model_name='user',
            name='assigned_devices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trials.device'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('RECEPTION', 'Receptionist'), ('COLLECTOR', 'Collection'), ('SETUP', 'Fixer')], default=None, max_length=1000, null=True, verbose_name='DEPARTMENT (staff)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gst',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='GST NUMBER '),
        ),
        migrations.AlterField(
            model_name='user',
            name='mpos_serial_number',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='MPOS SERIAL NUMBER (staff)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='PHONE NUMBER'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zone',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='ZONE'),
        ),
    ]
