# Generated by Django 4.0.6 on 2022-07-26 09:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0004_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='BOQUET NAME')),
                ('channels', models.ManyToManyField(blank=True, to='trials.channel', verbose_name='ADD CHANNEL')),
            ],
        ),
    ]
