# Generated by Django 4.0.6 on 2022-07-26 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0005_bouquet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='PLAN NAME')),
                ('types', models.CharField(blank=True, choices=[('1', 'Cable'), ('2', 'Broadband')], default=None, max_length=1000, null=True, verbose_name='TYPE')),
                ('bouqets', models.ManyToManyField(blank=True, to='trials.bouquet', verbose_name='BOQUET NAME')),
                ('channels', models.ManyToManyField(blank=True, to='trials.channel', verbose_name='CHANNEL NAME')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trials.plans', verbose_name='PLAN NAME')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer Name')),
            ],
        ),
    ]
