# Generated by Django 4.0.6 on 2022-07-26 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0008_bouquet_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Customer Name'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_ticket', models.CharField(blank=True, choices=[('1', 'AUDIO'), ('2', 'MESSAGE'), ('3', 'PICTURE')], default=None, max_length=1000, null=True, verbose_name='TYPE OF TICKET')),
                ('message', models.URLField()),
                ('status', models.CharField(blank=True, choices=[('1', 'OPEN'), ('2', 'CLOSED'), ('3', 'FAILED'), ('4', 'PENDING')], default=None, max_length=1000, null=True, verbose_name='TICKET STATUS')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Employee Name')),
                ('from_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_customer', to=settings.AUTH_USER_MODEL, verbose_name='Customer Name')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pgid', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='PAYMENT GATEWAY ID')),
                ('status', models.CharField(blank=True, choices=[('1', 'OPEN'), ('2', 'CLOSED'), ('3', 'FAILED'), ('4', 'PENDING')], default=None, max_length=1000, null=True, verbose_name='PAYMENT STATUS')),
                ('supscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trials.subscription', verbose_name='Subscription')),
            ],
        ),
    ]
