# Generated by Django 4.0.6 on 2022-07-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0009_alter_subscription_user_ticket_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
